"""Create snippets table

Revision ID: 943edfdd253d
Revises:
Create Date: 2025-07-14 00:06:22.864550

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "943edfdd253d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
