# fly.toml app configuration file generated for snipster-reflex on 2025-08-15T22:39:21-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'snipster-reflex'
primary_region = 'sjc'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    protocol = "http"
    method = "GET"
    path = "/ping"
    interval = "15s"
    timeout = "2s"
    grace_period = "30s"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
