name: Deploy Reflex App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Reflex Cloud
        uses: reflex-dev/reflex-deploy-action@v1
        with:
          auth_token: ${{ secrets.REFLEX_AUTH_TOKEN }}
          project_id: ${{ secrets.REFLEX_PROJECT_ID }}
          app_directory: "ui" # defaults to root
          extra_args: "--env API_BASE_URL=https://snipster-fastapi.fly.dev --envfile .reflex-cloud-env" # using both here not sure what works
          python_version: "3.13"
