name: Tests

on:
  push:
    branches:
      - stage
      - main
  pull_request:

  jobs:
    build:

      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Install uv
          uses: astral-sh/setup-uv@v3
          with:
            version: "0.8.12"
            enable-cache: true
            cache-dependency-glob: "uv.lock"

        - name: Set up Python
          run: uv python install

        - name: Install the project
          run: uv sync --all-extras --dev

        - name: Run tests
          run: uv run pytest tests -k "not test_e2e"
